version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://localhost:27017/to_do_list_db
  mongo:
    image: mongodb
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB: to_do_list_db